### ISSUE TITLE
Issue with Date/DateComponents/Calendar

### ISSUE THREAD

**Issue by kanchudeep** [SwiftForWindows/SwiftForWindows#34]
Are Date, DateComponents and Calendar implemented fully?

```swift
import Foundation
let calendar:Calendar = Calendar.init(identifier: .gregorian),
		dc:DateComponents = calendar.dateComponents([.year, .month, .day, .hour, .minute, .second], from: Date()),
		year:Int = dc.year!,
		month:Int = dc.month!,
		day:Int = dc.day!,
		hour:Int = dc.hour!,
		minute:Int = dc.minute!,
		second:Int = dc.second!
print("\(year)/\(month)/\(day) \(hour):\(minute):\(second)")
```
The above code results in `Successfully compiled` but trying to run the compiled `EXE` results in `test.exe has stopped working` with following log:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	test.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a485d8a
  Fault Module Name:	libswiftCore.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a1dd963
  Exception Code:	c0000005
  Exception Offset:	00000000002c8a68
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	16393
  Additional Information 1:	2a62
  Additional Information 2:	2a622f736c5aa4a6a3a49c7d1553befd
  Additional Information 3:	4265
  Additional Information 4:	42659591601f777d7a767fdef52146d3
```

**Comment by tinysun212** [comment]
Thanks for your reporting this bug.
I was able to reproduce the problem with your test code.
This bug has been fixed in my repo and the new package will be available in a day or two.

**Comment by tinysun212** [comment]
The new 'Swift for Windows v1.8' is released. It resolved the above bug and some bugs of the Foundation module. Would you try it?

**Comment by kanchudeep** [comment]
Will surely try it!

**Comment by kanchudeep** [comment]
Compiles successfully, but the `EXE` is still crashing with `test.exe has stopped working` with the following log:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	test.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a4c43b8
  Fault Module Name:	libFoundation.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a4b8af0
  Exception Code:	c000001d
  Exception Offset:	0000000000002cd0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	16393
  Additional Information 1:	7799
  Additional Information 2:	7799af66e180d6550622111d49f272cd
  Additional Information 3:	659f
  Additional Information 4:	659f44144034dd30c780073bd05b30f1
```

**Comment by tinysun212** [comment]
I couldn't reproduce your recently reported bug in my test environments.
Can you run it other PC?

**Comment by kanchudeep** [comment]
I don't have any another PC running Windows... I'm getting the same error in a virtual machine also.

Let me try it on another PC if possible...

**Comment by damuellen** [comment]
I've also tried it, and in my vm with Win7 x64 it runs without error.

**Comment by kanchudeep** [comment]
Tried again in a new VM...

Not working... Windows 7 x64 SP1... Clean install with only SwiftForWindows installed...

Tried both the `EXE` based installer and the `ZIP` based binary.

**Comment by tinysun212** [comment]
Could you capture the output of the `swift TestCode.swift` in the `Swift Tools Command Prompt`? The TestCode.swift is above code or as follows.
```
import Foundation
print(Date())
```
You can invoke the `Swift Tools Command Prompt` by double-clicking on the directory `c:\Swift`.

**Comment by kanchudeep** [comment]
This is the output for above:
```
Wrote crash dump file "C:\Users\Deep\AppData\Local\Temp\swift.exe-5a6e6d.dmp"
0x000000006D982CD0 (0x000000006DA2CF98 0x0000650073696C00 0x0000000000000000 0x00000000000E0080), __HALT
0x000000006DA2CA20 (0x0000000100000002 0x000000006A9E1825 0x000000000A899968 0x0000000000000000), CFStringCreateMutable() + 0x3D30 bytes(s)
0x000000006DA28CAA (0x000000006AA90E95 0x000000006DB81E6B 0x000000006D987F20 0x0000000000000173), _CFStringCreateWithFormatAndArgumentsAux2() + 0x10A bytes(s)
0x000000006DA2D2B5 (0x0000000000000000 0x000000000A899DB0 0x000000006D987D40 0x000000006E108176), CFStringCreateWithFormat() + 0x35 bytes(s)
0x000000006D9C8F77 (0x0000000000000002 0x000000006A9E3BE7 0x000000006AA90E95 0x000000006A9E1AC6), _CFTimeZoneInit() + 0x1037 bytes(s)
0x000000006D9C6CF3 (0x000000006E1A5238 0x0000000000000000 0x0000000000000001 0x000000006D987DDC), CFTimeZoneCreateWithName() + 0x283 bytes(s)
0x000000006D9C72F1 (0x0000000000000100 0x000000006D9878A9 0x0000000000000001 0x000000006D987CDC), CFTimeZoneCopySystem() + 0x191 bytes(s)
0x000000006D9C7523 (0x000000006A9F2DC0 0x000000006D98732D 0x0000000000000002 0x0000000000000020), CFTimeZoneCopyDefault() + 0x63 bytes(s)
0x000000006D9B18B8 (0x000000000694C070 0x000000006E168558 0x000000000A9FDAE0 0x000000006E168460), CFDateFormatterCreateISO8601Formatter() + 0x698 bytes(s)
0x000000006D9B1B32 (0x000000000694BFEF 0x000000000694C048 0x000000006E1683F8 0x000000006E168558), CFDateFormatterCreate() + 0x22 bytes(s)
0x000000006DBB7C32 (0x000000000694C050 0x000000000694C048 0x000000000694C000 0x000000000694C2E0), _T010Foundation6NSDateC11descriptionSSfg() + 0x42 bytes(s)
0x000000006DF673C4 (0x41C0016E26278E8F 0x000000006A899557 0x0000000000000002 0x0000000000000020), _T010Foundation4DateV12customMirrors0D0Vfg() + 0x394 bytes(s)
0x000000006A89957A (0x000000006AA8D890 0x000000006AA4B6C0 0x0000000000000018 0x00000000086E1DF0), _T0s15_print_unlockedyx_q_zts16TextOutputStreamR_r0_lFTfq4gn_n() + 0x4EA bytes(s)
0x000000006A940FE7 (0x000000006AA5DACF 0x0000000000000001 0x0000000000000000 0x000000000694C430), _T0s6_printySayypG_SS9separatorSS10terminatorxz2tots16TextOutputStreamRzlFs04_TeeG0VySSs7_StdoutVG_Tgq5Tfq4ggXgXn_n() + 0x137 bytes(s)
0x000000006A942098 (0x000000006AA5DACF 0x0000000000000001 0x0000000000000000 0x000000006A940EB0), _T0s10debugPrintySayypGd_SS9separatorSS10terminatortFTfq4ggXgX_n() + 0x128 bytes(s)
0x000000006A9414FF (0x000000006AA5DACF 0x0000000000000001 0x0000000000000000 0x000000006DF66BE6), _T0s5printySayypGd_SS9separatorSS10terminatortFTfq4ggXgX_n() + 0x4F bytes(s)
0x000000006A73E85E (0x000000006AA5DACF 0x0000000000000001 0x0000000000000000 0x0000000004189E6D), _T0s5printySayypGd_SS9separatorSS10terminatortF() + 0x3E bytes(s)
0x000000000B1700B5 (0x0000000000000001 0x0000000000000000 0x0000000004189E6D 0x000000000694C6D0) <unknown module>
0x000000006AA5DACF (0x0000000000000000 0x0000000004189E6D 0x000000000694C6D0 0x0000000000000020), _T0s9DecodableMp() + 0x5CF bytes(s)
0x0000000000000001 (0x0000000004189E6D 0x000000000694C6D0 0x0000000000000020 0x0000000000000001) <unknown module>
```
The generated file is also attached...
[swift.exe-5a6e6d.zip](https://github.com/SwiftForWindows/SwiftForWindows/files/1610292/swift.exe-5a6e6d.zip)

**Comment by tinysun212** [comment]
Thanks for your report. Thanks to that, I was able to reproduce a similar error.
My Windows 7 virtual machine didn't crash with your code, but Windows 7 and Windows 10 crashed with the following code.

```
// TestTimeZone.swift
import Foundation
print(TimeZone(identifier:"Asia/Seoul")!)
```
Since their call stacks are similar, I think your crash will be fixed if I fix my `TestTimeZone.swift`.
I'll notify you as soon as I fix it.

Thanks
Han Sangjin

**Comment by kanchudeep** [comment]
Oh! My pleasure to assist... Would be nice to have this fixed...

**Comment by tinysun212** [comment]
I modified the source code and build the new Foundation module.

You can download the new Foundation module `swift-foundation.zip` from [here](https://ci.appveyor.com/project/tinysun212/swift-foundation-builder/build/1.0.32/artifacts). (https://ci.appveyor.com/project/tinysun212/swift-foundation-builder/build/1.0.32/artifacts)
The zip file has no swift compiler and has only the Foundation module.
To install, extract the directories from the zip file and overwrite (not replace) them to `Swift\usr\bin` and `Swift\usr\lib`.

Could you test again and let me know the result?

**Comment by kanchudeep** [comment]
The code:

```swift
import Foundation
let calendar:Calendar = Calendar.init(identifier: .gregorian),
		dc:DateComponents = calendar.dateComponents([.year, .month, .day, .hour, .minute, .second], from: Date()),
		year:Int = dc.year!,
		month:Int = dc.month!,
		day:Int = dc.day!,
		hour:Int = dc.hour!,
		minute:Int = dc.minute!,
		second:Int = dc.second!
print("\(year)/\(month)/\(day) \(hour):\(minute):\(second)")
```

Now compiles and runs correctly!

Thanks...

**Comment by tinysun212** [comment]
Thanks for your tests.

`libFoundation.dll` will be exist in `Swift\usr\lib\swift\mingw`.
